version: '3.3'
services:
  mysqldb:
    container_name: dbswitch_mysqldb
    image: mysql:5.7
    volumes:
      - "/data/mysql:/var/lib/mysql"
    environment:
      MYSQL_DATABASE: dbswitch
      MYSQL_USER: tangyibo
      MYSQL_PASSWORD: 123456
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_ROOT_HOST: '%'
    ports:
      - 13306:3306
  dbswitch:
    container_name: dbswitch_webui
    image: inrgihc/dbswitch:1.6.4
    environment:
      MYSQLDB_HOST: dbswitch_mysqldb
      MYSQLDB_PORT: 3306
      MYSQLDB_USERNAME: tangyibo
      MYSQLDB_PASSWORD: 123456
    ports:
      - 9088:9088
    depends_on:
      - mysqldb

